core/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.views.static import serve
from django.conf.urls.i18n import i18n_patterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),

] + i18n_patterns(
    path('i18n/', include('django.conf.urls.i18n')),
    path('', include('main.urls')),

    prefix_default_language=False
)


urlpatterns += [re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT})]
urlpatterns += [re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT})]

main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.main, name='main'),
    path('about/', views.about, name='about'),
    path('news/', views.news, name='news'),
    path('news-detail/<pk>/', views.news_detail, name='news_detail'),
    path('teachers/', views.teachers, name='teachers'),
    path('categories/', views.categories, name='categories'),
    path('category/<pk>/', views.category, name='category'),
    path('docs/', views.docs, name='docs'),
    path('docs/<pk>/', views.docs_detail, name='docs_detail'),
]

main/models.py
from django.db import models


class Category(models.Model):
    name = models.CharField(verbose_name='Название', max_length=255)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'


# Doctype
class Doctype(models.Model):
    doctype_name = models.CharField(verbose_name='Тип документа', max_length=255)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='Категория')

    def __str__(self):
        return self.doctype_name

    class Meta:
        verbose_name = 'Тип документа'
        verbose_name_plural = 'Тип документы'


# Document
class Document(models.Model):
    IS_PUBLIC = (
        ('PUBLIC', 'Доступный'),
        ('PRIVATE', 'Не доступный'),
    )
    title = models.CharField(verbose_name='Тип документа', max_length=255)
    doctype = models.ForeignKey(Doctype, on_delete=models.CASCADE, verbose_name='Тип документа')
    is_public = models.CharField(verbose_name='Тип доступа', max_length=255,
                                 choices=IS_PUBLIC, default=IS_PUBLIC[0][1])
    description = models.TextField(verbose_name='Описание', blank=True, null=True)
    date_created = models.DateTimeField(verbose_name='Дата создание', auto_now_add=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Документ'
        verbose_name_plural = 'Документы'
        ordering = ('-date_created', )


class DocFile(models.Model):
    docs = models.ForeignKey(Document, on_delete=models.CASCADE)
    title = models.CharField(verbose_name='Название', max_length=255)
    file = models.FileField(verbose_name='Исходный файл', upload_to='main/docs/', blank=False, null=False)
    date_created = models.DateField(verbose_name='Дата создание', blank=True, null=True)

    def __str__(self):
        return self.docs.title

    class Meta:
        verbose_name = 'Файл'
        verbose_name_plural = 'Файлы'
        ordering = ('-date_created',)


# Teachers
class Teacher(models.Model):
    full_name = models.CharField(verbose_name='Полная имя', max_length=255)
    branch = models.CharField(verbose_name='Направление', max_length=255, default='')
    image = models.ImageField(verbose_name='Изображение', upload_to='main/authors/', blank=True, null=True)
    about = models.TextField(verbose_name='О педагоге', blank=True, null=True)

    def __str__(self):
        return self.full_name

    class Meta:
        verbose_name = 'Педагог'
        verbose_name_plural = 'Педагоги'


# News
class News(models.Model):
    title = models.CharField(verbose_name='Название темы', max_length=255)
    poster = models.ImageField(verbose_name='Постер', upload_to='main/news/poster/', blank=True, null=True)
    description = models.TextField(verbose_name='Описание', blank=True, null=True)
    date_created = models.DateTimeField(verbose_name='Дата создание', auto_now_add=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Новость'
        verbose_name_plural = 'Новости'
        ordering = ('-date_created', )


# Gallery
class Gallery(models.Model):
    title = models.CharField(verbose_name='Название файла', max_length=255)
    file = models.FileField(verbose_name='Исходный файл', upload_to='main/gallery/', blank=False, null=False)
    description = models.TextField(verbose_name='Описание', blank=True, null=True)
    active = models.BooleanField(verbose_name='Активный', default=False)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Галерея'
        verbose_name_plural = 'Галереи'

main/views.py
from django.shortcuts import render, get_object_or_404
from .models import Doctype, Document, Teacher, News, Gallery, Category


def main(request):
    news = News.objects.all()[:4]

    # context
    context = {
        'news': news,

        'categories': Category.objects.all(),
        'last_doctype_list': Doctype.objects.all()[:5],
        'last_document_list': Document.objects.filter(is_public='PUBLIC')[:5],
        'last_teachers': Teacher.objects.all()[:4],
        'last_gallery': Gallery.objects.all()[:4]
    }
    return render(request, 'main/index.html', context)


def about(request):

    # context
    context = {
        'categories': Category.objects.all(),
        'last_doctype_list': Doctype.objects.all()[:5],
        'last_document_list': Document.objects.filter(is_public='PUBLIC')[:5],
        'last_gallery': Gallery.objects.all()[:4]
    }
    return render(request, 'main/about.html', context)


def news(request):
    news = News.objects.all()

    # context
    context = {
        'news': news,

        'categories': Category.objects.all(),
        'last_doctype_list': Doctype.objects.all()[:5],
        'last_document_list': Document.objects.filter(is_public='PUBLIC')[:5],
        'last_gallery': Gallery.objects.all()[:4]
    }
    return render(request, 'main/news.html', context)


def news_detail(request, pk):
    post = get_object_or_404(News, pk=pk)

    context = {
        'post': post,

        'categories': Category.objects.all(),
        'last_doctype_list': Doctype.objects.all()[:5],
        'last_document_list': Document.objects.filter(is_public='PUBLIC')[:5],
        'last_gallery': Gallery.objects.all()[:4]
    }
    return render(request, 'main/news_detail.html', context)


def teachers(request):
    teachers_list = Teacher.objects.all()

    # context
    context = {
        'teachers': teachers_list,

        'categories': Category.objects.all(),
        'last_doctype_list': Doctype.objects.all()[:5],
        'last_document_list': Document.objects.filter(is_public='PUBLIC')[:5],
        'last_gallery': Gallery.objects.all()[:4]
    }
    return render(request, 'main/teachers.html', context)


def categories(request):

    # context
    context = {
        'categories': Category.objects.all(),
        'last_doctype_list': Doctype.objects.all()[:5],
        'last_document_list': Document.objects.filter(is_public='PUBLIC')[:5],
        'last_gallery': Gallery.objects.all()[:4]
    }
    return render(request, 'main/categories.html', context)


def category(request, pk):
    doctype = get_object_or_404(Doctype, pk=pk)
    documents = doctype.document_set.filter(is_public='PUBLIC')

    # context
    context = {
        'doctype': doctype,
        'documents': documents,

        'categories': Category.objects.all(),
        'last_doctype_list': Doctype.objects.all()[:5],
        'last_document_list': Document.objects.filter(is_public='PUBLIC')[:5],
        'last_gallery': Gallery.objects.all()[:4]
    }
    return render(request, 'main/category.html', context)


def docs(request):

    # context
    context = {
        'categories': Category.objects.all(),
        'last_doctype_list': Doctype.objects.all()[:5],
        'last_document_list': Document.objects.all()[:5],
        'last_gallery': Gallery.objects.all()[:4]
    }
    return render(request, 'main/docs.html', context)


def docs_detail(request, pk):
    doc = get_object_or_404(Document, pk=pk, is_public='PUBLIC')

    # context
    context = {
        'doc': doc,
        'categories': Category.objects.all(),
        'last_doctype_list': Doctype.objects.all()[:5],
        'last_document_list': Document.objects.filter(is_public='PUBLIC')[:5],
        'last_gallery': Gallery.objects.all()[:4]
    }
    return render(request, 'main/doc_detail.html', context)

templates/main/about.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}

{% block title %}{% translate "О нас" %}{% endblock title %}

{% block content %}
    <div id="about">
        <div class="bg-white rounded-lg">
            <div class="p-4">
                <h2 class="mb-3 text-3xl font-bold tracking-tight text-gray-800 dark:text-white">
                    {% translate "О нас" %}
                </h2>
                <p class="text-gray-500 dark:text-gray-400">
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe, doloribus sint architecto, 
                    repudiandae ullam iure similique libero magnam dignissimos porro velit aliquam vel voluptatum ad 
                    odio error sequi soluta maxime consequatur amet consequuntur voluptas harum sed! Veritatis, earum animi.
                </p>
            </div>

            <img src="{% static '/images/about.jpeg' %}" alt="about">

            <div class="p-4">
                <p class="text-gray-500 dark:text-gray-400">
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe, doloribus sint architecto, 
                    repudiandae ullam iure similique libero magnam dignissimos porro velit aliquam vel voluptatum ad 
                    odio error sequi soluta maxime consequatur amet consequuntur voluptas harum sed! Veritatis, earum animi.
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe, doloribus sint architecto, 
                    repudiandae ullam iure similique libero magnam dignissimos porro velit aliquam vel voluptatum ad 
                    odio error sequi soluta maxime consequatur amet consequuntur voluptas harum sed! Veritatis, earum animi.
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe, doloribus sint architecto, 
                    repudiandae ullam iure similique libero magnam dignissimos porro velit aliquam vel voluptatum ad 
                    odio error sequi soluta maxime consequatur amet consequuntur voluptas harum sed! Veritatis, earum animi.
                </p>
            </div>
        </div>

        <div id="accordion-flush" 
            class="my-6"
            data-accordion="collapse"
            data-active-classes="bg-white dark:bg-gray-900 text-gray-900 dark:text-white"
            data-inactive-classes="text-gray-500 dark:text-gray-400">
            <h2 id="accordion-flush-heading-1">
                <button type="button"
                    class="flex items-center rounded-lg p-5 justify-between w-full font-medium text-left text-gray-500 border-b border-gray-200 dark:border-gray-700 dark:text-gray-400"
                    data-accordion-target="#accordion-flush-body-1" aria-expanded="true" aria-controls="accordion-flush-body-1">
                    <span>What is Flowbite?</span>
                    <svg data-accordion-icon class="w-6 h-6 rotate-180 shrink-0" fill="currentColor" viewBox="0 0 20 20"
                        xmlns="http://www.w3.org/2000/svg">
                        <path fill-rule="evenodd"
                            d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z"
                            clip-rule="evenodd"></path>
                    </svg>
                </button>
            </h2>
            <div id="accordion-flush-body-1" class="hidden" aria-labelledby="accordion-flush-heading-1">
                <div class="py-5 border-b border-gray-200 dark:border-gray-700">
                    <p class="mb-2 text-gray-500 dark:text-gray-400">Flowbite is an open-source library of interactive
                        components built on top of Tailwind CSS including buttons, dropdowns, modals, navbars, and more.</p>
                    <p class="text-gray-500 dark:text-gray-400">Check out this guide to learn how to <a
                            href="/docs/getting-started/introduction/"
                            class="text-blue-600 dark:text-blue-500 hover:underline">get started</a> and start developing
                        websites even faster with components on top of Tailwind CSS.</p>
                </div>
            </div>
            <h2 id="accordion-flush-heading-2">
                <button type="button"
                    class="flex items-center justify-between w-full rounded-lg p-5 font-medium text-left text-gray-500 border-b border-gray-200 dark:border-gray-700 dark:text-gray-400"
                    data-accordion-target="#accordion-flush-body-2" aria-expanded="false"
                    aria-controls="accordion-flush-body-2">
                    <span>Is there a Figma file available?</span>
                    <svg data-accordion-icon class="w-6 h-6 shrink-0" fill="currentColor" viewBox="0 0 20 20"
                        xmlns="http://www.w3.org/2000/svg">
                        <path fill-rule="evenodd"
                            d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z"
                            clip-rule="evenodd"></path>
                    </svg>
                </button>
            </h2>
            <div id="accordion-flush-body-2" class="hidden" aria-labelledby="accordion-flush-heading-2">
                <div class="py-5 border-b border-gray-200 dark:border-gray-700">
                    <p class="mb-2 text-gray-500 dark:text-gray-400">Flowbite is first conceptualized and designed using the
                        Figma software so everything you see in the library has a design equivalent in our Figma file.</p>
                    <p class="text-gray-500 dark:text-gray-400">Check out the <a href="https://flowbite.com/figma/"
                            class="text-blue-600 dark:text-blue-500 hover:underline">Figma design system</a> based on the
                        utility classes from Tailwind CSS and components from Flowbite.</p>
                </div>
            </div>
            <h2 id="accordion-flush-heading-3">
                <button type="button"
                    class="flex items-center justify-between w-full rounded-lg p-5 font-medium text-left text-gray-500 border-b border-gray-200 dark:border-gray-700 dark:text-gray-400"
                    data-accordion-target="#accordion-flush-body-3" aria-expanded="false"
                    aria-controls="accordion-flush-body-3">
                    <span>What are the differences between Flowbite and Tailwind UI?</span>
                    <svg data-accordion-icon class="w-6 h-6 shrink-0" fill="currentColor" viewBox="0 0 20 20"
                        xmlns="http://www.w3.org/2000/svg">
                        <path fill-rule="evenodd"
                            d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z"
                            clip-rule="evenodd"></path>
                    </svg>
                </button>
            </h2>
            <div id="accordion-flush-body-3" class="hidden" aria-labelledby="accordion-flush-heading-3">
                <div class="py-5 border-b border-gray-200 dark:border-gray-700">
                    <p class="mb-2 text-gray-500 dark:text-gray-400">The main difference is that the core components from
                        Flowbite are open source under the MIT license, whereas Tailwind UI is a paid product. Another
                        difference is that Flowbite relies on smaller and standalone components, whereas Tailwind UI offers
                        sections of pages.</p>
                    <p class="mb-2 text-gray-500 dark:text-gray-400">However, we actually recommend using both Flowbite,
                        Flowbite Pro, and even Tailwind UI as there is no technical reason stopping you from using the best of
                        two worlds.</p>
                    <p class="mb-2 text-gray-500 dark:text-gray-400">Learn more about these technologies:</p>
                    <ul class="pl-5 text-gray-500 list-disc dark:text-gray-400">
                        <li><a href="https://flowbite.com/pro/"
                                class="text-blue-600 dark:text-blue-500 hover:underline">Flowbite Pro</a></li>
                        <li><a href="https://tailwindui.com/" rel="nofollow"
                                class="text-blue-600 dark:text-blue-500 hover:underline">Tailwind UI</a></li>
                    </ul>
                </div>
            </div>
        </div>
          
    </div>
{% endblock content %}

templates/main/categories.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}{% translate "Все категории" %}{% endblock title %}

{% block content %}
    <div id="categories">
        <div id="categories">
            <div class="flex justify-between items-center mb-4 bg-white p-4 rounded-lg shadow">
                <h1 class="ml-2 font-bold text-2xl text-gray-800">{% translate "Все категории" %}</h1>
            </div>

            <div
                class="p-4 bg-white border border-gray-200 rounded-lg shadow sm:p-8 dark:bg-gray-800 dark:border-gray-700">
                <div class="flow-root">
                    <ul role="list" class="divide-y divide-gray-200 dark:divide-gray-700">
                        {% for doctype in last_doctype_list %}
                            <li class="py-3 sm:py-4">
                                <div class="flex items-center space-x-4">
                                    <div class="flex-shrink-0">
                                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                                            <path stroke-linecap="round" stroke-linejoin="round" d="M9 12h3.75M9 15h3.75M9 18h3.75m3 .75H18a2.25 2.25 0 002.25-2.25V6.108c0-1.135-.845-2.098-1.976-2.192a48.424 48.424 0 00-1.123-.08m-5.801 0c-.065.21-.1.433-.1.664 0 .414.336.75.75.75h4.5a.75.75 0 00.75-.75 2.25 2.25 0 00-.1-.664m-5.8 0A2.251 2.251 0 0113.5 2.25H15c1.012 0 1.867.668 2.15 1.586m-5.8 0c-.376.023-.75.05-1.124.08C9.095 4.01 8.25 4.973 8.25 6.108V8.25m0 0H4.875c-.621 0-1.125.504-1.125 1.125v11.25c0 .621.504 1.125 1.125 1.125h9.75c.621 0 1.125-.504 1.125-1.125V9.375c0-.621-.504-1.125-1.125-1.125H8.25zM6.75 12h.008v.008H6.75V12zm0 3h.008v.008H6.75V15zm0 3h.008v.008H6.75V18z" />
                                        </svg>
                                    </div>
                                    <div class="flex-1 min-w-0">
                                        <p class="text-base font-bold text-gray-900 truncate dark:text-white">
                                            {{ doctype.doctype_name }}
                                        </p>
                                        <p class="text-sm text-gray-500 truncate dark:text-gray-400">
                                            {{ doctype.category }}
                                        </p>
                                    </div>
                                    <a href="{% url 'category' doctype.id %}" class="font-medium text-blue-600 dark:text-blue-500 hover:underline">{% translate "Перейти" %}</a>
                                </div>
                            </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

templates/main/category.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}{{ doctype.doctype_name }}{% endblock title %}

{% block content %}
    <div id="categories">
        <div id="categories">
            <div class="flex justify-between items-center mb-4 bg-white p-4 rounded-lg shadow">
                <h1 class="ml-2 font-bold text-2xl text-gray-800">{{ doctype.doctype_name }}</h1>
            </div>

            <div
                class="p-4 bg-white border border-gray-200 rounded-lg shadow sm:p-8 dark:bg-gray-800 dark:border-gray-700">
                <div class="flow-root">
                    <ul role="list" class="divide-y divide-gray-200 dark:divide-gray-700">
                        {% for doc in documents %}
                            <li class="py-3 sm:py-4">
                                <div class="flex items-center space-x-4">
                                    <div class="flex-shrink-0">
                                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                                            <path stroke-linecap="round" stroke-linejoin="round" d="M19.5 14.25v-2.625a3.375 3.375 0 00-3.375-3.375h-1.5A1.125 1.125 0 0113.5 7.125v-1.5a3.375 3.375 0 00-3.375-3.375H8.25m2.25 0H5.625c-.621 0-1.125.504-1.125 1.125v17.25c0 .621.504 1.125 1.125 1.125h12.75c.621 0 1.125-.504 1.125-1.125V11.25a9 9 0 00-9-9z" />
                                        </svg>
                                    </div>
                                    <div class="flex-1 min-w-0">
                                        <p class="text-base font-bold text-gray-900 truncate dark:text-white">
                                            {{ doc.title }}
                                        </p>
                                        <p class="text-sm text-gray-500 truncate dark:text-gray-400">
                                            {{ doctype.doctype_name }}
                                        </p>
                                    </div>
                                    <a href="{% url 'docs_detail' doc.id %}" class="font-medium text-blue-600 dark:text-blue-500 hover:underline">{% translate "Перейти" %}</a>
                                </div>
                            </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

templates/main/doc_detail.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}{{ doc.title }}{% endblock title %}

{% block content %}
<!-- Documents -->
<div id="documents" class="">
    <div class="flex justify-between items-center mb-4 bg-white p-4 rounded-lg shadow">
        <h1 class="ml-2 font-bold text-2xl text-gray-800">{{ doc.title }}</h1>
    </div>

    <div class="p-4 bg-white border border-gray-200 rounded-lg shadow sm:p-8 dark:bg-gray-800 dark:border-gray-700">
        <div class="flow-root">
            <ul role="list" class="divide-y divide-gray-200 dark:divide-gray-700">
                {% for file in doc.docfile_set.all %}
                <li class="py-3 sm:py-4">
                    <div class="flex items-center space-x-4">
                        <div class="flex-shrink-0">
                            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                                <path stroke-linecap="round" stroke-linejoin="round" d="M3 16.5v2.25A2.25 2.25 0 005.25 21h13.5A2.25 2.25 0 0021 18.75V16.5M16.5 12L12 16.5m0 0L7.5 12m4.5 4.5V3" />
                            </svg>
                        </div>
                        <div class="flex-1 min-w-0">
                            <p class="text-base font-bold text-gray-900 truncate dark:text-white">
                                {{ file.title }}
                            </p>
                            <p class="text-sm text-gray-500 truncate dark:text-gray-400">
                                {{ file.date_created }}
                            </p>
                        </div>
                        <a 
                            href="{{ file.file.url }}"
                            class="font-medium text-blue-600 dark:text-blue-500 hover:underline">
                            {% translate "Скачать" %}
                        </a>
                    </div>
                </li>
                {% endfor %}
            </ul>
        </div>
    </div>
</div>
{% endblock content %}

templates/main/docs.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}{% translate "Все документы" %}{% endblock title %}

{% block content %}
    <!-- Documents -->
    <div id="documents" class="mt-4">
        <div class="flex justify-between items-center mb-4 bg-white p-4 rounded-lg shadow">
            <h1 class="ml-2 font-bold text-2xl text-gray-800">{% translate "Все документы" %}</h1>
        </div>

        <div
            class="p-4 bg-white border border-gray-200 rounded-lg shadow sm:p-8 dark:bg-gray-800 dark:border-gray-700">
            <div class="flow-root">
                <ul role="list" class="divide-y divide-gray-200 dark:divide-gray-700">
                    {% for doc in last_document_list %}
                        <li class="py-3 sm:py-4">
                            <div class="flex items-center space-x-4">
                                <div class="flex-shrink-0">
                                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                                        <path stroke-linecap="round" stroke-linejoin="round" d="M19.5 14.25v-2.625a3.375 3.375 0 00-3.375-3.375h-1.5A1.125 1.125 0 0113.5 7.125v-1.5a3.375 3.375 0 00-3.375-3.375H8.25m2.25 0H5.625c-.621 0-1.125.504-1.125 1.125v17.25c0 .621.504 1.125 1.125 1.125h12.75c.621 0 1.125-.504 1.125-1.125V11.25a9 9 0 00-9-9z" />
                                    </svg>
                                </div>
                                <div class="flex-1 min-w-0">
                                    <p class="text-base font-bold text-gray-900 truncate dark:text-white">
                                        {{ doc.title }}
                                    </p>
                                    <p class="text-sm text-gray-500 truncate dark:text-gray-400">
                                        {{ doc.doctype }}
                                    </p>
                                </div>
                                <a href="{% url 'docs_detail' doc.id %}" class="font-medium text-blue-600 dark:text-blue-500 hover:underline">{% translate "Перейти" %}</a>
                            </div>
                        </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
{% endblock content %}

templates/main/news.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}{% translate "Все новости" %}{% endblock title %}

{% block content %}
    <div id="news">
        <div class="flex justify-between items-center bg-white p-4 rounded-lg shadow mb-4">
            <h1 class="ml-2 font-bold text-xl md:text-2xl text-gray-800">{% translate "Все новости" %}</h1>
        </div>

        <div id="news-content" class="grid grid-cols-1 sm:grid-cols-2 gap-2">
            <!-- List -->
            {% for post in news %}
                <div class="bg-white border border-gray-200 rounded-lg shadow dark:bg-gray-800 dark:border-gray-700">
                    <a href="{% url 'news_detail' post.id %}">
                        <img class="rounded-t-lg" src="{{ post.poster.url }}" alt="" />
                    </a>
                    <div class="p-5">
                        <a href="#">
                            <h5 class="mb-2 text-xl font-bold tracking-tight text-gray-900 dark:text-white">
                                {{ post.title }}
                            </h5>
                        </a>
                        <p class="mb-3 font-normal text-sm text-gray-700 dark:text-gray-400">{{ post.date_created }}</p>
                        <a href="{% url 'news_detail' post.id %}"
                            class="inline-flex items-center px-3 py-2 text-sm font-medium text-center text-white bg-blue-700 rounded-lg hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
                            Читать полностью
                            <svg aria-hidden="true" class="w-4 h-4 ml-2 -mr-1" fill="currentColor" viewBox="0 0 20 20"
                                xmlns="http://www.w3.org/2000/svg">
                                <path fill-rule="evenodd"
                                    d="M10.293 3.293a1 1 0 011.414 0l6 6a1 1 0 010 1.414l-6 6a1 1 0 01-1.414-1.414L14.586 11H3a1 1 0 110-2h11.586l-4.293-4.293a1 1 0 010-1.414z"
                                    clip-rule="evenodd"></path>
                            </svg>
                        </a>
                    </div>
                </div>
            {% endfor %}

        </div>
    </div>
{% endblock content %}

templates/main/news_detail.html
{% extends 'base.html' %}

{% block title %}{{ post.title }}{% endblock title %}

{% block content %}
    <!-- News -->
    <div id="documents" class="">
        <div class="flex justify-between items-center mb-4 bg-white p-4 rounded-lg shadow">
            <h1 class="ml-2 font-bold text-2xl text-gray-800">{{ post.title }}</h1>
        </div>

        <div class="bg-white border border-gray-200 rounded-lg shadow dark:bg-gray-800 dark:border-gray-700">
            <a href="#">
                <img class="rounded-t-lg" src="{% if post.poster.url %}{{ post.poster.url }}{% else %}https://flowbite.com/docs/images/blog/image-1.jpg{% endif %}" alt="" />
            </a>
            <div class="p-5">
                <h5 class="pb-4 text-xl border-b font-bold tracking-tight text-gray-900 dark:text-white">
                    {{ post.title }}
                </h5>
                <div class="py-4 border-b">{{ post.description | safe }}</div>
                <p class="pt-4 mb-3 font-normal text-sm text-gray-700 dark:text-gray-400">{{ post.date_created }}</p>
            </div>
        </div>
    </div>
{% endblock content %}